version: '3.3'

services:

  db-service:
    env_file:
      - .env
    profiles:
      - core
      - db
      - all
    user: postgres
    image: postgres:12.6
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - 'database-datastore:/var/lib/postgresql/data/'
    networks:
      - core-net


  redis-service:
    env_file:
      - .env
    profiles:
      - core
      - redis
      - all
    image: redis:6.2-alpine
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    command: redis-server --loglevel warning
    volumes:
      - 'redis_data:/bitnami/redis/data'
    ports:
      - '127.0.0.1:6379:6379'
    networks:
      - core-net

networks:
  core-net:
    external:
      name: core-net
    driver: bridge


volumes:
  database-datastore:
    driver: local
  redis_data:
      driver: local
