version: '3.3'

services:

  db-service:
    env_file:
      - .env-dev
    profiles:
      - core
      - db
      - all
    user: postgres
    image: postgres:12.6
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - 'database-datastore-4:/var/lib/postgresql/data/'
    networks:
      - core-net




networks:
  core-net:
    external:
      name: core-net
    driver: bridge


volumes:
  database-datastore-4:
    driver: local
