version: '3.3'

services:

  db-service:
    env_file:
      - .env
    profiles:
      - core
      - db
      - all
    user: postgres
    image: postgres:12.6
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - 'database-data:/var/lib/postgresql/data/'
    environment:
      - POSTGRES_PASSWORD=postgres

  redis-service:
    env_file:
      - .env
    profiles:
      - core
      - redis
      - all
    image: redis:6.2-alpine
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    command: redis-server --loglevel warning
    volumes:
      - 'redis_data:/bitnami/redis/data'
    ports:
      - '6379:6379'

  app-web:
    env_file:
      - .env
    profiles:
      - web
      - all
    build: ./
    command:
      - '/app/entrypoint/web-app-start.sh'
    volumes:
      - './storage/:/storage/'
    ports:
      - '2000:2000'
    depends_on:
      - redis-service
      - db-service

  celery-worker:
    env_file:
      - .env
    profiles:
      - worker
      - all
    build: ./
    command:
      - '/app/entrypoint/celery-start.sh'
    volumes:
      - './storage/:/storage/'
    ports:
      - '3000:3000'
    depends_on:
      - redis-service
      - db-service

volumes:
  database-data:
    driver: local
  redis_data:
    driver: local
  web_data:
    driver: local
