runtime: python
service: api-rest
instance_class: F2
env: flex
entrypoint: gunicorn -b :$PORT --workers 1 --threads 8 --timeout 160 app:app

runtime_config:
  python_version: 3.7

env_variables:
  POSTGRES_DB:
  POSTGRES_PASSWORD:
  POSTGRES_URL:
  POSTGRES_USER:
  REDIS_SERVER:
  REDIS_PORT:
  FLASK_ENV:
  FLASK_DEBUG:
  UPLOAD_FOLDER:
  CONVERTED_FOLDER:
  MAIL_NOTIFICATION_ENABLED:
  BUCKET_NAME:
  TOPIC:
  PROJECT_ID:

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 4
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6